default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-dromo_development

test:
  <<: *default
  database: rails-dromo_test

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
